app:
  name: cmf
  port: :8801
  debug: true
database:
  type: mysql
  host: localhost
  database: tenant_666666
  username: root
  password: 123456
  port: 3306
  charset: utf8mb4
  prefix: cmf_
  authcode: KFHlk2ubIlMr5ltqaD
